### PR TITLE
AUI-3203 Add semantic tag to minicalendar heading

### PR DESCRIPTION
**Pull request by orsolyaDekany**
Hello,
Accessibility evaluation tool found an error. To meet the criteria, we can add aria-level to heading role.
https://issues.liferay.com/browse/AUI-3203

The other option is to add semantic heading element instead of the div. I am not sure which would be a better choice here.

Can you please review it?
Thanks!

### CODE REVIEW

**Comment by nhpatt** [comment]
Can you check it @edalgrin ?

**Comment by nhpatt** [comment]
This repo hasn't been updated in 5 years... so if we can fix it in another way it would be desirable...

**Review by edalgrin — COMMENTED** [review]
The change is ok, Ideally we should use `<h1>` instead of `<div role="heading" aria-level="1" ...` but I guess we couldn't do that for some reason.

> This repo hasn't been updated in 5 years... so if we can fix it in another way it would be desirable...

It's hard to tell without knowing the context, if we needed a quick "green light" on the test we could hide this content from assistive technology using `aria-hidden="true"` on the parent element that calls this part but I can't tell if this info is necessary for the understanding of the "page".

**Comment by nhpatt** [comment]
Any other way to solve it @orsolyaDekany ? As I mentioned this project is not being updated and if we can avoid doing a release for that small fix it would be preferable.

**Comment by orsolyaDekany** [comment]
Hi @nhpatt @edalgrin ,
just so you know context, this header template is **the heading (month) of the minicalendar**. This is where the user sees which month is currently chosen, so it is a necessary information. As far as I know, aria-hidden would ignore it, so that does not seem a good option here. 
I modified the fix from adding `aria-level` to `<h1>` instead (based on importance of the section). Font-size style is already applied for the element, so this change will not effect the heading size. 
Sorry, but I do not know any other way to fix it, this seems the only way. If the fix looks good, can you please push this forward? Thank you.
heading

**Review by edalgrin — APPROVED** [review]

**Comment by orsolyaDekany** [comment]
Hi @nhpatt @edalgrin , 
I can see that you approved the changes, but the PR has not been merged yet. Can you please let me know when can I expect to move this PR forward and when can I expect a new version release? I am also asking, because we opened a bug ticket for the issue due to customer request, so we need to inform the customer with updates. Thanks for your answer!

**Comment by bryceosterhaus** [comment]
Hey @orsolyaDekany, sorry for the delay in getting back to you. I am just looking into this now.

Is it possible to just override the `HEADER_TEMPLATE` where we use this module? 

```js
Y.CalendarBase.HEADER_TEMPLATE = '<div class="yui3-g {calendar_hd_class}">' +
                        '<h1 class="yui3-u {calendar_hd_label_class}" id="{calendar_id}_header">' +
                            '{calheader}' +
                        '</h1>' +
                    '</div>';


new Y.CalendarBase(
//...
);
```

**Comment by orsolyaDekany** [comment]
Hi @bryceosterhaus , thanks for getting back to me. I am looking into other way to change this, in the calendar-web module. Chema gave me some guidance on this, let's see how can I manage that.

**Pull request closed without merging**
