### PR TITLE
fix: Avoid focusing on modal instead of field on specific cases

### PR DESCRIPTION
**Pull request by icgsbr**
https://liferay.atlassian.net/browse/LPP-50079

### CODE REVIEW

**Comment by antonio-ortega** [comment]
Hey @icgsbr ,

i've been checking this case and I don't really think this is the right solution.

We are updating something really deep into our code and used massively to fix something that's only happening in Forms when using a custom [DropdownListWithSearch](https://github.com/liferay/liferay-portal-ee/blob/7.3.x/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/main/resources/META-INF/resources/Select/Select.es.js#L250) component. 

Have you tried to manage the focus in that component? I think that would be much safer.

If you have tried and see something why that could not be a solution, let me know, please.

Thanks.

Regards.

**Comment by icgsbr** [comment]
Hi @antonio-ortega !

Though this solution is not ideal, it's the one we could find that solves the reported issue.

What is going on is that some part of the code is hijacking the focus from the field and sending it to the modal; therefore, even if we try to force the focus event on DropdownListWithSearch, it will still focus on the modal since this behavior is coming from a deeper part of the code.

The solution contained in the sent commit was recommended by an engineer from frontend-infra through a PTR, which was opened after we exhausted our attempts to fix it at our side.

If you need any more information or have a better approach idea, feel free to contact me.

Best regards.

**Comment by antonio-ortega** [comment]
Hi @icgsbr ,

This is a specific issue in that dropdown and it should be fixed there. 

As an example on how to do it, you can see [this example](https://github.com/antonio-ortega/liferay-portal-ee/commit/a05c7bcfab6aee871aa9c95648dd3e79f3195384), just by doing that you are able to focus on search input.

It is not working on the first click, but that's because you have another issue with that dropdown because you are not focusing on it when it gets opened. But as soon as you fix that, you'll see how with that code it's enough to fix this focus issue without patching YUI.

I'm closing this pull request now, since the code I linked above proofs this can be fixed and it should be fixed within that specific component.

Thanks.

Regards.

Pd: Btw, in that commit I linked above there is a modification on MAX_ITEMS constant. Just ignore it. That's not needed at all.

**Comment by icgsbr** [comment]
Hi @antonio-ortega !

I here again to ask for your help concerning this solution. Indeed what you proposed on this [commit](https://github.com/antonio-ortega/liferay-portal-ee/commit/a05c7bcfab6aee871aa9c95648dd3e79f3195384) works, yet only on the second click due to the fact the dropdown isn't being focused

**Comment by icgsbr** [comment]
Hi, Antonio Ortega!

I'm here again to ask for your help concerning this solution. Indeed, what you proposed on https://github.com/antonio-ortega/liferay-portal-ee/commit/a05c7bcfab6aee871aa9c95648dd3e79f3195384 works, yet only on the second click due to the fact the dropdown isn't being focused when opened. I tried a lot to fix the mentioned issue with help from other frontend engineers, but, unfortunately, I got no success in solving it. Could you please help me on this matter?

**Comment by antonio-ortega** [comment]
Hey @icgsbr ,

Are you sure this issue is still reproducible?

I've just compiled current master branch ([commit](https://github.com/liferay/liferay-portal/commit/ee303dbf5d7a3c23dfc86c727bb4c78ed894e749)) and follow the steps in [LPP-50079](https://liferay.atlassian.net/browse/LPP-50079) and I can no longer reproduce it, so it seems like some changes were introduced in Forms in the last two weeks fixing this.

Thanks.

Regards.

**Comment by icgsbr** [comment]
ci:test:close

**Comment by icgsbr** [comment]
ci:close

**Pull request closed without merging**
